version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    # env_file:
    #     - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=Ifra123%40
      - DATABASE_NAME=FastAPI
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=ajndsmdscmbmfbskdjalskadcxmcx
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRATION_MINUTES=30

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Ifra123%40
      - POSTGRES_DB=FastAPI
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: