name: Build and Deploy Code

on: [push, pull_request]

  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v2
      
      - name: Say hit to Ifra
      - run: echo "Hey there, I'm Ifra here!"